### ISSUE TITLE
How are the boards made?

### ISSUE THREAD

**Issue by drudru** [wickerwaka/PicoROM#1]
Hi, are you getting the boards assembled or are you doing the SMT soldering when you receive the boards?

**Comment by wickerwaka** [comment]
No way could I solder these myself without a new set of eyes and just the right amount of alcohol in my system!

I use JLCPCB to do the assembly. BOM, CPL and Gerber files are here: https://github.com/wickerwaka/PicoROM/tree/main/hardware/jlcpcb/production_files

**Comment by drudru** [comment]
Heh - I am in the same boat soldering wise.
Thanks for pointing me in the right direction.
