### ISSUE TITLE
emulate a 16 k Bit EPROM with a standard Raspberry Pi Pico

### ISSUE THREAD

**Issue by OE4DEA** [wickerwaka/PicoROM#3]
I have the use case to emulate a 16 k Bit EPROM with a standard Raspberry Pi Pico. Would this be possible by modifying the GPIOs in the system.h file or would major adjustments have to be made?

**Comment by wickerwaka** [comment]
It could be made to work, but a 16KBit EPROM would have a much smaller footprint since it doesn't need as many address pins. Fitting everything into that smaller footprint would be very difficult.

**Comment by OE4DEA** [comment]
Since I want to use the standard Raspberry Pi Pico, I don’t see any mechanical problems. My question is more about what adjustments need to be made to the software.

**Comment by wickerwaka** [comment]
The software assumes the presence of external buffer on the data pins, so you would need to change to code to account for that. Older versions of the code worked without it and there are defines you can change to re-enable that support, but it is untested.
